### ISSUE TITLE
Issues with docker run

### ISSUE THREAD

**Issue by benkeser** [HuiqingSun/INFO550-Final-Project-renv#1]
A couple issues:

- [This line](https://github.com/HuiqingSun/INFO550-Final-Project-renv/blob/52b0975f0d9f0229ac7d5ee7bb3f824741fbd0d3/makefile#L45) should be
```
	docker run -v "/$$(pwd)/final_report":/project/final_report hqsun/hdp
```
Here, I've added a `/` in front of `$$(pwd)` so that it works on git bash and I have removed the space `: /project` -> `:/project`

- Please remove the compiled report (`final_report/report.html`) from the github repository otherwise the make command will not update the file. `git rm final_report/report.html` `git commit -m "remove"` and re-push.

Otherwise was able to build the report.

Re: your other question about instructions for build -- it does not have to be much. See e.g., https://github.com/kcamp27/final-project for an example that received full marks.

**Comment by HuiqingSun** [comment]
Issue solved! Thank you so much!
